import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
import sharp from 'sharp';

const root = new URL('../', import.meta.url);
const assets = {};
for (const id of ['iceberg', 'coastal-house']) {
  const source = await fs.readFile(new URL(`public/scenes/${id}/source.png`, root));
  const encoded = await sharp(source).webp({ lossless: true, effort: 6 }).toBuffer();
  const before = await sharp(source).ensureAlpha().raw().toBuffer();
  const after = await sharp(encoded).ensureAlpha().raw().toBuffer();
  if (!before.equals(after) || encoded.length >= source.length) throw new Error(`Invalid photo optimization: ${id}`);
  const hash = createHash('sha256').update(encoded).digest('hex').slice(0, 12);
  assets[id] = `/delivery/photo-${id}-${hash}.webp`;
  await fs.writeFile(new URL(`public${assets[id]}`, root), encoded);
  console.log(`${id}: ${source.length} -> ${encoded.length} bytes; decoded pixels identical`);
}
await fs.writeFile(new URL('src/photo-assets.js', root), `// Generated by scripts/optimize-photos.mjs; original photographs remain intact.\nexport default ${JSON.stringify(assets, null, 2)};\n`);
