// Generated by scripts/optimize-photos.mjs; original photographs remain intact.
export default {
  "iceberg": "/delivery/photo-iceberg-e5fbab56a581.webp",
  "coastal-house": "/delivery/photo-coastal-house-db40ff9498c9.webp"
};
